apiVersion: v1
kind: Namespace
metadata:
  name: pam-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      containers:
      - name: pubsub
        image: piotrsicinski/pubsub:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: pubsub-service
  namespace: pam-ns
spec:
  selector:
    app: pubsub
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer
  template:
    metadata:
      labels:
        app: streamer
    spec:
      containers:
      - name: streamer
        image: piotrsicinski/streamer:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: streamer-service
  namespace: pam-ns
spec:
  selector:
    app: streamer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30002
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: piotrsicinski/server:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: pam-ns
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30003
  type: NodePort

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pam-base-deployment
#   namespace: pam-ns
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pam-base
#   template:
#     metadata:
#       labels:
#         app: pam-base
#     spec:
#       containers:
#       - name: pam-base
#         image: piotrsicinski/pam-base:latest
#         ports:
#         - containerPort: 8083

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: pam-base-service
#   namespace: pam-ns
# spec:
#   selector:
#     app: pam-base
#   ports:
#   - protocol: TCP
#     port: 8083
#     targetPort: 8083
#     nodePort: 30004
#   type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications
        image: piotrsicinski/notifications:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: pam-ns
spec:
  selector:
    app: notifications
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30005
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-ai-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-ai
  template:
    metadata:
      labels:
        app: model-ai
    spec:
      containers:
      - name: model-ai
        image: piotrsicinski/model_ai:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: model-ai-service
  namespace: pam-ns
spec:
  selector:
    app: model-ai
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30006
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamenager-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datamenager
  template:
    metadata:
      labels:
        app: datamenager
    spec:
      containers:
      - name: datamenager
        image: piotrsicinski/datamenager:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: datamenager-service
  namespace: pam-ns
spec:
  selector:
    app: datamenager
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizeuser-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorizeuser
  template:
    metadata:
      labels:
        app: authorizeuser
    spec:
      containers:
      - name: authorizeuser
        image: piotrsicinski/authorizeuser:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: authorizeuser-service
  namespace: pam-ns
spec:
  selector:
    app: authorizeuser
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30008
  type: NodePort
