apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongodb/mongodb-community-server
        ports:
        - containerPort: 27017
          name: mongodb
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: pam-ns
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongodb
  type: LoadBalancer
