# docker.io/piotrsicinski
# piotrsicinski

apiVersion: v1
kind: Namespace
metadata:
  name: pam-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: piotrsicinski/server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: pam-ns
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30003
  type: NodePort