apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: piotrsicinski/server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      imagePullSecrets:
      - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: pam-ns
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30003
  type: NodePort

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa
  namespace: pam-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      containers:
      - name: pubsub
        image: piotrsicinski/pubsub:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      imagePullSecrets:
      - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: pubsub-service
  namespace: pam-ns
spec:
  selector:
    app: pubsub
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer
  template:
    metadata:
      labels:
        app: streamer
    spec:
      containers:
      - name: streamer
        image: piotrsicinski/streamer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      imagePullSecrets:
      - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: streamer-service
  namespace: pam-ns
spec:
  selector:
    app: streamer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30002
    name: http
  - protocol: TCP
    port: 1935
    targetPort: 1935
    nodePort: 31935
    name: rtsp
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications
        image: piotrsicinski/notifications:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      imagePullSecrets:
      - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: pam-ns
spec:
  selector:
    app: notifications
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30005
    name: http
  - protocol: TCP
    port: 8765
    targetPort: 8765
    nodePort: 30765
    name: websocket
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-ai-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-ai
  template:
    metadata:
      labels:
        app: model-ai
    spec:
      containers:
      - name: model-ai
        image: piotrsicinski/model_ai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      imagePullSecrets:
      - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: model-ai-service
  namespace: pam-ns
spec:
  selector:
    app: model-ai
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30006
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamenager-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datamenager
  template:
    metadata:
      labels:
        app: datamenager
    spec:
      containers:
      - name: datamenager
        image: piotrsicinski/datamenager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      imagePullSecrets:
      - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: datamenager-service
  namespace: pam-ns
spec:
  selector:
    app: datamenager
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizeuser-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorizeuser
  template:
    metadata:
      labels:
        app: authorizeuser
    spec:
      containers:
      - name: authorizeuser
        image: piotrsicinski/authorizeuser:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      imagePullSecrets:
      - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: authorizeuser-service
  namespace: pam-ns
spec:
  selector:
    app: authorizeuser
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30008
  type: NodePort