apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: pam-ns
data:
  mosquitto.conf: |
    # Zawartość twojego pliku mosquitto.conf
    listener 1883
    allow_anonymous true
    # Dodaj inne opcje konfiguracyjne tutaj

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 9001
          name: websocket
        resources:
          requests:
            cpu: "500m"
            memory: "400Mi"
          limits:
            cpu: "1000m"
            memory: "800Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: config-volume
        configMap:
          name: mosquitto-config
      imagePullSecrets:
      - name: docker-secret

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: pam-ns
spec:
  selector:
    app: mosquitto
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
    name: mqtt
  - protocol: TCP
    port: 9001
    targetPort: 9001
    name: websocket
  type: LoadBalancer
