apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: docker.io/mongodb/mongodb-community-server
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "500m"
            memory: "400Mi"
          limits:
            cpu: "1000m"
            memory: "800Mi"
      imagePullSecrets:
      - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: pam-ns
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 32717
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mariadb
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: "500m"
            memory: "400Mi"
          limits:
            cpu: "1000m"
            memory: "800Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
      imagePullSecrets:
      - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: pam-ns
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3333
    targetPort: 3306
    nodePort: 30333
  type: NodePort