apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: pam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:22.04
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "--"]
        args: [
          "apt-get update && apt-get install -y iputils-ping && apt-get install -y net-tools && apt-get install -y curl && \
          while true; do echo hello; sleep 10; done;"
        ]
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      imagePullSecrets:
      - name: docker-secret


---

apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  namespace: pam-ns
spec:
  selector:
    app: ubuntu
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
